
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import wosaa_fashion_store_is.BinarySearch;
import wosaa_fashion_store_is.MergeSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * Title: Wosaa Fashion Store Information System
 * Part: Main GUI
 * @author 19030375 Anwesh Dahal
 * @author 19030875 Bishesh Dangol
 * @author 19031389 Pratik Amatya
 * @author 19031710 Srijan Adhikari
 */
public class WosaaFSInfo extends javax.swing.JFrame {

    /**
     * Creates new form WosaaFSInfo
     */
    public WosaaFSInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBG = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        tableTitleLBL = new javax.swing.JLabel();
        controlsTbP = new javax.swing.JTabbedPane();
        addItemPane = new javax.swing.JPanel();
        addItemLBL = new javax.swing.JLabel();
        idLBL = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        nameLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        brandLBL = new javax.swing.JLabel();
        brandTF = new javax.swing.JTextField();
        typeLBL = new javax.swing.JLabel();
        typeCB = new javax.swing.JComboBox<>();
        genderLBL = new javax.swing.JLabel();
        menRB = new javax.swing.JRadioButton();
        womenRB = new javax.swing.JRadioButton();
        unisexRB = new javax.swing.JRadioButton();
        sizeLBL = new javax.swing.JLabel();
        xsChkB = new javax.swing.JCheckBox();
        sChkB = new javax.swing.JCheckBox();
        mChkB = new javax.swing.JCheckBox();
        lChkB = new javax.swing.JCheckBox();
        xlChkB = new javax.swing.JCheckBox();
        xxlChkB = new javax.swing.JCheckBox();
        xxxLChkB = new javax.swing.JCheckBox();
        priceLBL = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        itemIDValidationLBL = new javax.swing.JLabel();
        brandValidationLBL = new javax.swing.JLabel();
        genderValidationLBL = new javax.swing.JLabel();
        typeValidationLBL = new javax.swing.JLabel();
        sizeValidationLBL = new javax.swing.JLabel();
        priceValidationLBL = new javax.swing.JLabel();
        nameValidationLBL = new javax.swing.JLabel();
        searchItemPane = new javax.swing.JPanel();
        searchItemLBL = new javax.swing.JLabel();
        searchPriceValidationLBL = new javax.swing.JLabel();
        searchItemByPriceLBL = new javax.swing.JLabel();
        priceSearchTF = new javax.swing.JTextField();
        searchPriceBTN = new javax.swing.JButton();
        searchItemByTypeLBL = new javax.swing.JLabel();
        searchTypeValidationLBL = new javax.swing.JLabel();
        typeSearchCB = new javax.swing.JComboBox<>();
        searchTypeBTN = new javax.swing.JButton();
        mainMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wosaa Fashion Store - Inventory Information System");

        itemTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Brand", "Type", "Gender", "Size", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemTable.setShowGrid(true);
        jScrollPane1.setViewportView(itemTable);

        tableTitleLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableTitleLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableTitleLBL.setText("Wosaa Fashion Store - Inormation System");

        controlsTbP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addItemLBL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addItemLBL.setText("Add New Item");

        idLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idLBL.setText("Item ID");

        idTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idTFKeyReleased(evt);
            }
        });

        nameLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameLBL.setText("Item Name");

        nameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTFKeyReleased(evt);
            }
        });

        brandLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        brandLBL.setText("Item Brand");

        brandTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        brandTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                brandTFKeyReleased(evt);
            }
        });

        typeLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        typeLBL.setText("Item Type");

        typeCB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        typeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Type --", "T-Shirt", "Shirt", "Sweater", "Jacket", "Pants", "Coat" }));

        genderLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        genderLBL.setText("Item Gender");

        genderBG.add(menRB);
        menRB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        menRB.setText("Men");

        genderBG.add(womenRB);
        womenRB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        womenRB.setText("Women");

        genderBG.add(unisexRB);
        unisexRB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        unisexRB.setText("Unisex");

        sizeLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sizeLBL.setText("Item Size");

        xsChkB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        xsChkB.setText("XS");

        sChkB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sChkB.setText("S");

        mChkB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mChkB.setText("M");

        lChkB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lChkB.setText("L");

        xlChkB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        xlChkB.setText("XL");

        xxlChkB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        xxlChkB.setText("XXL");

        xxxLChkB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        xxxLChkB.setText("XXXL");

        priceLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        priceLBL.setText("Item Price");

        priceTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        priceTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceTFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priceTFKeyReleased(evt);
            }
        });

        addBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        clearBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearBTN.setText("Clear");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        itemIDValidationLBL.setForeground(new java.awt.Color(255, 0, 0));

        brandValidationLBL.setForeground(new java.awt.Color(255, 0, 0));

        genderValidationLBL.setForeground(new java.awt.Color(255, 0, 0));

        typeValidationLBL.setForeground(new java.awt.Color(255, 0, 51));

        sizeValidationLBL.setForeground(new java.awt.Color(255, 0, 0));

        priceValidationLBL.setForeground(new java.awt.Color(255, 0, 0));

        nameValidationLBL.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout addItemPaneLayout = new javax.swing.GroupLayout(addItemPane);
        addItemPane.setLayout(addItemPaneLayout);
        addItemPaneLayout.setHorizontalGroup(
            addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItemPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addItemPaneLayout.createSequentialGroup()
                        .addComponent(clearBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBTN))
                    .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addItemLBL)
                        .addGroup(addItemPaneLayout.createSequentialGroup()
                            .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sizeLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(typeLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(brandLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(genderLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idTF)
                                    .addComponent(nameTF)
                                    .addComponent(brandTF)
                                    .addComponent(typeCB, 0, 226, Short.MAX_VALUE)
                                    .addGroup(addItemPaneLayout.createSequentialGroup()
                                        .addComponent(menRB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(womenRB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(unisexRB)))
                                .addGroup(addItemPaneLayout.createSequentialGroup()
                                    .addComponent(xsChkB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sChkB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mChkB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lChkB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(xlChkB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(xxlChkB))
                                .addComponent(xxxLChkB)))
                        .addGroup(addItemPaneLayout.createSequentialGroup()
                            .addComponent(priceLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addComponent(nameValidationLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brandValidationLBL)
                    .addComponent(itemIDValidationLBL)
                    .addComponent(genderValidationLBL)
                    .addComponent(typeValidationLBL)
                    .addComponent(sizeValidationLBL)
                    .addComponent(priceValidationLBL))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        addItemPaneLayout.setVerticalGroup(
            addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItemPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addItemLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLBL)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemIDValidationLBL))
                .addGap(17, 17, 17)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLBL)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameValidationLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandValidationLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 12, Short.MAX_VALUE)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLBL)
                    .addComponent(typeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeValidationLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLBL)
                    .addComponent(menRB)
                    .addComponent(womenRB)
                    .addComponent(unisexRB)
                    .addComponent(genderValidationLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 12, Short.MAX_VALUE)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeLBL)
                    .addComponent(xsChkB)
                    .addComponent(sChkB)
                    .addComponent(mChkB)
                    .addComponent(lChkB)
                    .addComponent(xlChkB)
                    .addComponent(xxlChkB)
                    .addComponent(sizeValidationLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                .addComponent(xxxLChkB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLBL)
                    .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceValidationLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBTN)
                    .addComponent(clearBTN))
                .addContainerGap())
        );

        controlsTbP.addTab("Add New Item", addItemPane);

        searchItemLBL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchItemLBL.setText("Search Item");

        searchPriceValidationLBL.setForeground(new java.awt.Color(255, 0, 51));

        searchItemByPriceLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchItemByPriceLBL.setText("Search Item By Price");

        priceSearchTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        priceSearchTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceSearchTFKeyPressed(evt);
            }
        });

        searchPriceBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchPriceBTN.setText("Search");
        searchPriceBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPriceBTNActionPerformed(evt);
            }
        });

        searchItemByTypeLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchItemByTypeLBL.setText("Search Item By Type");

        searchTypeValidationLBL.setForeground(new java.awt.Color(255, 0, 51));

        typeSearchCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Type --", "T-Shirt", "Shirt", "Sweater", "Jacket", "Pants", "Coat" }));

        searchTypeBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchTypeBTN.setText("Search");
        searchTypeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTypeBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchItemPaneLayout = new javax.swing.GroupLayout(searchItemPane);
        searchItemPane.setLayout(searchItemPaneLayout);
        searchItemPaneLayout.setHorizontalGroup(
            searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchItemPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(searchItemByTypeLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchItemByPriceLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(searchItemLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTypeValidationLBL)
                    .addGroup(searchItemPaneLayout.createSequentialGroup()
                        .addGroup(searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(priceSearchTF)
                            .addComponent(typeSearchCB, 0, 185, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchPriceBTN)
                            .addComponent(searchTypeBTN)))
                    .addComponent(searchPriceValidationLBL))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        searchItemPaneLayout.setVerticalGroup(
            searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchItemPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchItemPaneLayout.createSequentialGroup()
                        .addComponent(searchItemLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchItemPaneLayout.createSequentialGroup()
                        .addComponent(searchPriceValidationLBL)
                        .addGap(2, 2, 2)))
                .addGroup(searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchItemByPriceLBL)
                    .addComponent(priceSearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPriceBTN))
                .addGap(2, 2, 2)
                .addComponent(searchTypeValidationLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchItemByTypeLBL)
                    .addComponent(typeSearchCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTypeBTN))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        controlsTbP.addTab("Search Item", searchItemPane);

        fileMenu.setText("File");

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        exitMenuItem.setText("Exit");
        fileMenu.add(exitMenuItem);

        mainMenu.add(fileMenu);

        helpMenu.setText("Help");
        mainMenu.add(helpMenu);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(tableTitleLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controlsTbP)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tableTitleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlsTbP)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchPriceBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPriceBTNActionPerformed
        String search_price = priceSearchTF.getText();
        
        if (!search_price.isEmpty()) {
            searchPrice(Integer.parseInt(search_price));
        } else {
            searchPriceValidationLBL.setText("*Required Field");
            searchPriceValidationLBL.grabFocus();
            JOptionPane.showMessageDialog(null,"The price field must not be left empty.","Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_searchPriceBTNActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        //Clear Button
        idTF.setText("");
        nameTF.setText("");
        brandTF.setText("");
        typeCB.setSelectedIndex(0);
        genderBG.clearSelection();
        xsChkB.setSelected(false);
        sChkB.setSelected(false);
        lChkB.setSelected(false);
        mChkB.setSelected(false);
        xlChkB.setSelected(false);
        xxlChkB.setSelected(false);
        xxxLChkB.setSelected(false);
        priceTF.setText("");
    }//GEN-LAST:event_clearBTNActionPerformed
    
    
    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        String item_id = idTF.getText();
        String item_name = nameTF.getText();
        String item_brand = brandTF.getText();

        String item_type = (String) typeCB.getSelectedItem();

        //To get the selected gender
        String item_gender = "";
        if (menRB.isSelected()) {
            item_gender = menRB.getText();
        }
        if (womenRB.isSelected()) {
            item_gender = womenRB.getText();
        }
        if (unisexRB.isSelected()) {
            item_gender = unisexRB.getText();
        }
        String item_size = "";

        if (xsChkB.isSelected()){
            item_size = item_size + xsChkB.getText() + ",";
        }
        if (sChkB.isSelected()){
            item_size = item_size + sChkB.getText() + ",";
        }
        if (mChkB.isSelected()){
            item_size = item_size + mChkB.getText() + ",";
        }
        if (lChkB.isSelected()){
            item_size = item_size + lChkB.getText() + ",";
        }
        if (xlChkB.isSelected()){
            item_size = item_size + xlChkB.getText() + ",";
        }
        if (xxlChkB.isSelected()){
            item_size = item_size + xxlChkB.getText() + ",";
        }

        if (item_size.length() != 0) {
            item_size = item_size.substring(0, item_size.length() - 1);
        }

        String item_price = priceTF.getText();

        //Adding data into jTable
        int nextRow = 0;
        boolean empty = false;
        String s;
        int rows = itemTable.getRowCount();
        int colCount = itemTable.getColumnCount();

        if (!item_id.isEmpty()){
            if (!item_name.isEmpty()) {
                if (!item_brand.isEmpty()) {
                    if (typeCB.getSelectedIndex() != 0) {
                        if (!item_gender.isEmpty()) {
                            if (!item_size.isEmpty()) {
                                if (!item_price.isEmpty()) {
                                    String data [] = {item_id, item_name, item_brand, item_type, item_gender, item_size, item_price};
                                    Warning();
                                        
                                    do {
                                        s =(String) itemTable.getValueAt (nextRow, 0);
                                        if (s != null && s.length() != 0) {
                                            nextRow++;
                                        } else {
                                            empty = true;
                                        }
                                    }while (nextRow < rows && !empty);
                                     if (nextRow >= rows && !empty) {
                                         DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
                                         model.addRow(data);
                                         
                                     }else {
                                         for (int i = 0; i < colCount; i++) {
                                             itemTable.setValueAt(data[i], nextRow, i);
                                         }
                                     }
                                } else {
                                    Warning();
                                    priceValidationLBL.setText("*Required Field");
                                    JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Please fill in the price of the item.","Alert",JOptionPane.WARNING_MESSAGE);
                                }
                            } else {
                                sizeValidationLBL.setText("*Required Field");
                                itemIDValidationLBL.setText("");
                                nameValidationLBL.setText("");
                                brandValidationLBL.setText("");
                                typeValidationLBL.setText("");
                                genderValidationLBL.setText("");
                                priceValidationLBL.setText("");
                                JOptionPane.showMessageDialog(null,"Please select one or more than one size option.","Alert",JOptionPane.WARNING_MESSAGE);
                            }
                        }else {
                            genderValidationLBL.setText("*Required Field");
                            itemIDValidationLBL.setText("");
                            nameValidationLBL.setText("");
                            brandValidationLBL.setText("");
                            typeValidationLBL.setText("");
                            sizeValidationLBL.setText("");
                            priceValidationLBL.setText("");
                            JOptionPane.showMessageDialog(null,"Please select any one of the gender option.","Alert",JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        typeValidationLBL.setText("*Required Field");
                        itemIDValidationLBL.setText("");
                        nameValidationLBL.setText("");
                        brandValidationLBL.setText("");
                        genderValidationLBL.setText("");
                        sizeValidationLBL.setText("");
                        priceValidationLBL.setText("");
                        JOptionPane.showMessageDialog(null,"Please select the type of item.","Alert",JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    brandValidationLBL.setText("*Required Field");
                    brandTF.grabFocus();
                    itemIDValidationLBL.setText("");
                    nameValidationLBL.setText("");
                    typeValidationLBL.setText("");
                    genderValidationLBL.setText("");
                    sizeValidationLBL.setText("");
                    priceValidationLBL.setText("");
                    JOptionPane.showMessageDialog(null,"Please fill in the brand of the item.","Alert",JOptionPane.WARNING_MESSAGE);
                }
            } else {
                nameValidationLBL.setText("*Required Field");
                nameTF.grabFocus();
                itemIDValidationLBL.setText("");
                brandValidationLBL.setText("");
                typeValidationLBL.setText("");
                genderValidationLBL.setText("");
                sizeValidationLBL.setText("");
                priceValidationLBL.setText("");
                JOptionPane.showMessageDialog(null,"Please fill in the name of the item.","Alert",JOptionPane.WARNING_MESSAGE);
            }
        } else {
            itemIDValidationLBL.setText("*Required Field");
            idTF.grabFocus();
            nameValidationLBL.setText("");
            brandValidationLBL.setText("");
            typeValidationLBL.setText("");
            genderValidationLBL.setText("");
            sizeValidationLBL.setText("");
            priceValidationLBL.setText("");
            JOptionPane.showMessageDialog(null,"Please fill in the id of the item.","Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addBTNActionPerformed

    public void Warning() {
        itemIDValidationLBL.setText("");
        nameValidationLBL.setText("");
        brandValidationLBL.setText("");
        typeValidationLBL.setText("");
        genderValidationLBL.setText("");
        sizeValidationLBL.setText("");
        priceValidationLBL.setText("");
    }
    private void idTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTFKeyPressed
        char a = evt.getKeyChar();
        if (Character.isDigit(a)||evt.getKeyCode()==8) {
            idTF.setEditable(true);
        } else {
            idTF.setEditable(false);
        }
    }//GEN-LAST:event_idTFKeyPressed

    private void priceTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTFKeyPressed
        char a = evt.getKeyChar();
        if (Character.isDigit(a)||evt.getKeyCode()==8) {
            priceTF.setEditable(true);
        } else {
            priceTF.setEditable(false);
        }
    }//GEN-LAST:event_priceTFKeyPressed

    private void priceSearchTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceSearchTFKeyPressed
        char a = evt.getKeyChar();
        if (Character.isDigit(a)||evt.getKeyCode()==8) {
            priceSearchTF.setEditable(true);
        } else {
            priceSearchTF.setEditable(false);
        }
    }//GEN-LAST:event_priceSearchTFKeyPressed

    private void searchTypeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTypeBTNActionPerformed
        String search_type = (String) typeSearchCB.getSelectedItem();
        
        if (typeSearchCB.getSelectedIndex() != 0) {
        
        } else {
            searchTypeValidationLBL.setText("*Required Field");
            JOptionPane.showMessageDialog(null,"The type of the item should not be left empty.","Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_searchTypeBTNActionPerformed

    private void idTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTFKeyReleased
        // TODO add your handling code here:
        itemIDValidationLBL.setText("");
    }//GEN-LAST:event_idTFKeyReleased

    private void nameTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTFKeyReleased
        // TODO add your handling code here:
        nameValidationLBL.setText("");
    }//GEN-LAST:event_nameTFKeyReleased

    private void brandTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandTFKeyReleased
        // TODO add your handling code here:
        brandValidationLBL.setText("");
    }//GEN-LAST:event_brandTFKeyReleased

    private void priceTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTFKeyReleased
        // TODO add your handling code here:
        priceValidationLBL.setText("");
    }//GEN-LAST:event_priceTFKeyReleased
    
    private void searchPrice(int price){
        // Check if the table contains data
        Object checkObj = itemTable.getValueAt(0, 0);
        if (checkObj == null){
            JOptionPane.showMessageDialog(null,"There are no items to search","Alert",JOptionPane.WARNING_MESSAGE);
            return;
        }
            
        // Total number of rows in the table
        int totalRows = itemTable.getRowCount();
        // Number of columns in the table
        int columns = 7;
        // Number of filled row
        int rows = findFilledRows(totalRows);
        // Getting the number of filled rows
        Object[][] itemsArray = new Object[rows][columns];
        
        // Insert Data into an array for search
        for (int i = 0; i < rows; i++){
            for (int j = 0; j < columns; j++){
                itemsArray[i][j] = itemTable.getValueAt(i, j);
            }
        }
        // Sorting the itemsArray using MergeSort
        MergeSorter.sort(itemsArray);
        
        for (int i = 0; i < rows; i++){
            for (int j = 0; j < columns; j++){
                System.out.print(itemsArray[i][j] + "| " );
            }
            System.out.println("");
        }
        
        // lowest index of the array, defaults to 0
        int low = 0;
        
        // highest index of the array, equals length of array -1
        int high = itemsArray.length - 1;
        
        // searching the item in the array using binary search
        int ansPos = BinarySearch.search(itemsArray, low, high, price);
   
        
        
        /**
         * Since the binary search may not return the first occurrence of the
         * item with same price in the items table the value of first
         * occurrence is determined by the following loop
         */
        System.out.println(ansPos);
        
        while (ansPos < itemsArray.length - 1){
            if (Integer.parseInt((String) itemsArray[ansPos + 1][6]) == price){
                System.out.println(itemsArray[ansPos][6]);
                ansPos++;
            } else{
                break;
            }
        }
        
        System.out.println(ansPos);
        
        Object[] targetItem = itemsArray[ansPos];
        
        String display = "Item Found:" + 
                            "\nItem ID: " + targetItem[0] + 
                            "\nItem Name: " + targetItem[1] +
                            "\nItem Brand: " + targetItem[2] +
                            "\nItem Type: " + targetItem[3] +
                            "\nItem Gender: " + targetItem[4] +
                            "\nItem Sizes: " + targetItem[5] +
                            "\nItem Price: " + targetItem[6];
        
        System.out.println(display);
        
        JOptionPane.showMessageDialog(addItemPane, display);
        
                
        System.out.println("Rows: " + rows + ", Columns: " + columns);
    }
    
    private int findFilledRows(int totalRows){
        int rows = 0;
        for (int i = 0; i < totalRows; i++){
            // Only the item at index 0 is checked because 
            // the validation during the insertion assures that
            // all of the columns on the rows have data in them
            Object checkRowObj = itemTable.getValueAt(i,0);
            if (checkRowObj != null){
                rows++;
            } else{
                // Stop checking after a null value is found
                break;
            }
        }
       return rows; 
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WosaaFSInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WosaaFSInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WosaaFSInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WosaaFSInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WosaaFSInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel addItemLBL;
    private javax.swing.JPanel addItemPane;
    private javax.swing.JLabel brandLBL;
    private javax.swing.JTextField brandTF;
    private javax.swing.JLabel brandValidationLBL;
    private javax.swing.JButton clearBTN;
    private javax.swing.JTabbedPane controlsTbP;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.ButtonGroup genderBG;
    private javax.swing.JLabel genderLBL;
    private javax.swing.JLabel genderValidationLBL;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel idLBL;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel itemIDValidationLBL;
    private javax.swing.JTable itemTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox lChkB;
    private javax.swing.JCheckBox mChkB;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JRadioButton menRB;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel nameValidationLBL;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JLabel priceLBL;
    private javax.swing.JTextField priceSearchTF;
    private javax.swing.JTextField priceTF;
    private javax.swing.JLabel priceValidationLBL;
    private javax.swing.JCheckBox sChkB;
    private javax.swing.JLabel searchItemByPriceLBL;
    private javax.swing.JLabel searchItemByTypeLBL;
    private javax.swing.JLabel searchItemLBL;
    private javax.swing.JPanel searchItemPane;
    private javax.swing.JButton searchPriceBTN;
    private javax.swing.JLabel searchPriceValidationLBL;
    private javax.swing.JButton searchTypeBTN;
    private javax.swing.JLabel searchTypeValidationLBL;
    private javax.swing.JLabel sizeLBL;
    private javax.swing.JLabel sizeValidationLBL;
    private javax.swing.JLabel tableTitleLBL;
    private javax.swing.JComboBox<String> typeCB;
    private javax.swing.JLabel typeLBL;
    private javax.swing.JComboBox<String> typeSearchCB;
    private javax.swing.JLabel typeValidationLBL;
    private javax.swing.JRadioButton unisexRB;
    private javax.swing.JRadioButton womenRB;
    private javax.swing.JCheckBox xlChkB;
    private javax.swing.JCheckBox xsChkB;
    private javax.swing.JCheckBox xxlChkB;
    private javax.swing.JCheckBox xxxLChkB;
    // End of variables declaration//GEN-END:variables
}
