package wosaa_fashion_store_is;

/**
 *
 * Wosaa Fashion Store Information System
 * @author 19030375 Anwesh Dahal
 * @author 19030875 Bishesh Dangol
 * @author 19031389 Pratik Amatya
 * @author 19031710 Srijan Adhikari
 */
public class WosaaFSInfo extends javax.swing.JFrame {

    /**
     * Creates new form WosaaFSInfo
     */
    public WosaaFSInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBG = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        tableTitleLBL = new javax.swing.JLabel();
        controlsTbP = new javax.swing.JTabbedPane();
        addItemPane = new javax.swing.JPanel();
        addItemLBL = new javax.swing.JLabel();
        idLBL = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        itemIDValidationLBL = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        nameValidationLBL = new javax.swing.JLabel();
        brandLBL = new javax.swing.JLabel();
        brandTF = new javax.swing.JTextField();
        brandValidationLBL = new javax.swing.JLabel();
        typeLBL = new javax.swing.JLabel();
        typeCB = new javax.swing.JComboBox<>();
        typeValidationLBL = new javax.swing.JLabel();
        genderLBL = new javax.swing.JLabel();
        menRB = new javax.swing.JRadioButton();
        womenRB = new javax.swing.JRadioButton();
        unisexRB = new javax.swing.JRadioButton();
        genderValidationLBL = new javax.swing.JLabel();
        sizeLBL = new javax.swing.JLabel();
        xsChkB = new javax.swing.JCheckBox();
        sChkB = new javax.swing.JCheckBox();
        mChkB = new javax.swing.JCheckBox();
        lChkB = new javax.swing.JCheckBox();
        xlChkB = new javax.swing.JCheckBox();
        xxlChkB = new javax.swing.JCheckBox();
        xxxLChkB = new javax.swing.JCheckBox();
        sizeValidationLBL = new javax.swing.JLabel();
        priceLBL = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        priceValidationLBL = new javax.swing.JLabel();
        addBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        searchItemPane = new javax.swing.JPanel();
        searchItemLBL = new javax.swing.JLabel();
        searchPriceValidationLBL = new javax.swing.JLabel();
        searchItemByPriceLBL = new javax.swing.JLabel();
        priceSearchTF = new javax.swing.JTextField();
        searchPriceBTN = new javax.swing.JButton();
        searchItemByTypeLBL = new javax.swing.JLabel();
        searchTypeValidationLBL = new javax.swing.JLabel();
        typeSearchCB = new javax.swing.JComboBox<>();
        searchTypeBTN = new javax.swing.JButton();
        mainMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wosaa Fashion Store - Inventory Information System");
        setAlwaysOnTop(true);

        itemTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Brand", "Type", "Gender", "Size", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(itemTable);

        tableTitleLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableTitleLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableTitleLBL.setText("Wosaa Fashion Store - Inormation System");

        controlsTbP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addItemLBL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addItemLBL.setText("Add New Item");

        idLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idLBL.setText("Item ID");

        idTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        itemIDValidationLBL.setForeground(new java.awt.Color(255, 0, 51));
        itemIDValidationLBL.setText("* Required Field");

        nameLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameLBL.setText("Item Name");

        nameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        nameValidationLBL.setForeground(new java.awt.Color(255, 0, 51));
        nameValidationLBL.setText("* Required Field");

        brandLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        brandLBL.setText("Item Brand");

        brandTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        brandValidationLBL.setForeground(new java.awt.Color(255, 0, 51));
        brandValidationLBL.setText("* Required Field");

        typeLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        typeLBL.setText("Item Type");

        typeCB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        typeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Type --", "T-Shirt", "Shirt", "Sweater", "Jacket", "Pants", "Coat" }));

        typeValidationLBL.setForeground(new java.awt.Color(255, 0, 51));
        typeValidationLBL.setText("* Required Field");

        genderLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        genderLBL.setText("Item Gender");

        genderBG.add(menRB);
        menRB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        menRB.setText("Men");

        genderBG.add(womenRB);
        womenRB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        womenRB.setText("Women");

        genderBG.add(unisexRB);
        unisexRB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        unisexRB.setText("Unisex");

        genderValidationLBL.setForeground(new java.awt.Color(255, 0, 51));
        genderValidationLBL.setText("* Required Field");

        sizeLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sizeLBL.setText("Item Size");

        xsChkB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        xsChkB.setText("XS");

        sChkB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sChkB.setText("S");

        mChkB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mChkB.setText("M");

        lChkB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lChkB.setText("L");

        xlChkB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        xlChkB.setText("XL");

        xxlChkB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        xxlChkB.setText("XXL");

        xxxLChkB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        xxxLChkB.setText("XXXL");

        sizeValidationLBL.setForeground(new java.awt.Color(255, 0, 51));
        sizeValidationLBL.setText("* Required Field/ Select At Least 1");

        priceLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        priceLBL.setText("Item Price");

        priceTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        priceValidationLBL.setForeground(new java.awt.Color(255, 0, 51));
        priceValidationLBL.setText("* Required Field");

        addBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addBTN.setText("Add");

        clearBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearBTN.setText("Clear");

        javax.swing.GroupLayout addItemPaneLayout = new javax.swing.GroupLayout(addItemPane);
        addItemPane.setLayout(addItemPaneLayout);
        addItemPaneLayout.setHorizontalGroup(
            addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItemPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addItemPaneLayout.createSequentialGroup()
                        .addComponent(clearBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBTN))
                    .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addItemLBL)
                        .addGroup(addItemPaneLayout.createSequentialGroup()
                            .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sizeLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(typeLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(brandLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(genderLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idTF)
                                    .addComponent(nameTF)
                                    .addComponent(brandTF)
                                    .addComponent(typeCB, 0, 226, Short.MAX_VALUE)
                                    .addGroup(addItemPaneLayout.createSequentialGroup()
                                        .addComponent(menRB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(womenRB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(unisexRB)))
                                .addGroup(addItemPaneLayout.createSequentialGroup()
                                    .addComponent(xsChkB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sChkB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mChkB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lChkB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(xlChkB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(xxlChkB))
                                .addComponent(xxxLChkB)))
                        .addGroup(addItemPaneLayout.createSequentialGroup()
                            .addComponent(priceLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemIDValidationLBL)
                    .addComponent(nameValidationLBL)
                    .addComponent(brandValidationLBL)
                    .addComponent(typeValidationLBL)
                    .addComponent(genderValidationLBL)
                    .addComponent(sizeValidationLBL)
                    .addComponent(priceValidationLBL))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        addItemPaneLayout.setVerticalGroup(
            addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItemPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addItemLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLBL)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemIDValidationLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameValidationLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLBL)
                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brandValidationLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(brandLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(brandTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeValidationLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(typeLBL)
                        .addComponent(typeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderValidationLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(genderLBL)
                        .addComponent(menRB)
                        .addComponent(womenRB)
                        .addComponent(unisexRB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sizeValidationLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sizeLBL)
                        .addComponent(xsChkB)
                        .addComponent(sChkB)
                        .addComponent(mChkB)
                        .addComponent(lChkB)
                        .addComponent(xlChkB)
                        .addComponent(xxlChkB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xxxLChkB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLBL)
                    .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceValidationLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBTN)
                    .addComponent(clearBTN))
                .addContainerGap())
        );

        controlsTbP.addTab("Add New Item", addItemPane);

        searchItemLBL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchItemLBL.setText("Search Item");

        searchPriceValidationLBL.setForeground(new java.awt.Color(255, 0, 51));
        searchPriceValidationLBL.setText("* Required Field");

        searchItemByPriceLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchItemByPriceLBL.setText("Search Item By Price");

        priceSearchTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        searchPriceBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchPriceBTN.setText("Search");
        searchPriceBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPriceBTNActionPerformed(evt);
            }
        });

        searchItemByTypeLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchItemByTypeLBL.setText("Search Item By Type");

        searchTypeValidationLBL.setForeground(new java.awt.Color(255, 0, 51));
        searchTypeValidationLBL.setText("* Required Field");

        typeSearchCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Type --", "T-Shirt", "Shirt", "Sweater", "Jacket", "Pants", "Coat" }));

        searchTypeBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchTypeBTN.setText("Search");

        javax.swing.GroupLayout searchItemPaneLayout = new javax.swing.GroupLayout(searchItemPane);
        searchItemPane.setLayout(searchItemPaneLayout);
        searchItemPaneLayout.setHorizontalGroup(
            searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchItemPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(searchItemByTypeLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchItemByPriceLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(searchItemLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTypeValidationLBL)
                    .addGroup(searchItemPaneLayout.createSequentialGroup()
                        .addGroup(searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(priceSearchTF)
                            .addComponent(typeSearchCB, 0, 185, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchPriceBTN)
                            .addComponent(searchTypeBTN)))
                    .addComponent(searchPriceValidationLBL))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        searchItemPaneLayout.setVerticalGroup(
            searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchItemPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchItemPaneLayout.createSequentialGroup()
                        .addComponent(searchItemLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchItemPaneLayout.createSequentialGroup()
                        .addComponent(searchPriceValidationLBL)
                        .addGap(2, 2, 2)))
                .addGroup(searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchItemByPriceLBL)
                    .addComponent(priceSearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPriceBTN))
                .addGap(2, 2, 2)
                .addComponent(searchTypeValidationLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchItemByTypeLBL)
                    .addComponent(typeSearchCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTypeBTN))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        controlsTbP.addTab("Search Item", searchItemPane);

        fileMenu.setText("File");

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        exitMenuItem.setText("Exit");
        fileMenu.add(exitMenuItem);

        mainMenu.add(fileMenu);

        helpMenu.setText("Help");
        mainMenu.add(helpMenu);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(tableTitleLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controlsTbP)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tableTitleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlsTbP)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchPriceBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPriceBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPriceBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WosaaFSInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WosaaFSInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WosaaFSInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WosaaFSInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WosaaFSInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel addItemLBL;
    private javax.swing.JPanel addItemPane;
    private javax.swing.JLabel brandLBL;
    private javax.swing.JTextField brandTF;
    private javax.swing.JLabel brandValidationLBL;
    private javax.swing.JButton clearBTN;
    private javax.swing.JTabbedPane controlsTbP;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.ButtonGroup genderBG;
    private javax.swing.JLabel genderLBL;
    private javax.swing.JLabel genderValidationLBL;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel idLBL;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel itemIDValidationLBL;
    private javax.swing.JTable itemTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox lChkB;
    private javax.swing.JCheckBox mChkB;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JRadioButton menRB;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel nameValidationLBL;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JLabel priceLBL;
    private javax.swing.JTextField priceSearchTF;
    private javax.swing.JTextField priceTF;
    private javax.swing.JLabel priceValidationLBL;
    private javax.swing.JCheckBox sChkB;
    private javax.swing.JLabel searchItemByPriceLBL;
    private javax.swing.JLabel searchItemByTypeLBL;
    private javax.swing.JLabel searchItemLBL;
    private javax.swing.JPanel searchItemPane;
    private javax.swing.JButton searchPriceBTN;
    private javax.swing.JLabel searchPriceValidationLBL;
    private javax.swing.JButton searchTypeBTN;
    private javax.swing.JLabel searchTypeValidationLBL;
    private javax.swing.JLabel sizeLBL;
    private javax.swing.JLabel sizeValidationLBL;
    private javax.swing.JLabel tableTitleLBL;
    private javax.swing.JComboBox<String> typeCB;
    private javax.swing.JLabel typeLBL;
    private javax.swing.JComboBox<String> typeSearchCB;
    private javax.swing.JLabel typeValidationLBL;
    private javax.swing.JRadioButton unisexRB;
    private javax.swing.JRadioButton womenRB;
    private javax.swing.JCheckBox xlChkB;
    private javax.swing.JCheckBox xsChkB;
    private javax.swing.JCheckBox xxlChkB;
    private javax.swing.JCheckBox xxxLChkB;
    // End of variables declaration//GEN-END:variables
}
